@extends('admin.sidebar')

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/admin/home/reports/reports.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/admin/home/reports/total_sales.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endpush

@section('title', 'iStock | Reports')

@section('content')
@php
  $admin = auth()->guard('admin')->user();

  $reportCards = [
    ['title' => 'Total Sales', 'value' => '₱12.00', 'sub' => '₱12.00 is Highest'],
    ['title' => 'Gross Profit (Selling Price - Cost Price)', 'value' => '₱0.00', 'sub' => ''],
    ['title' => 'Profits ( Sales - Expense )', 'value' => 'No Expenses', 'sub' => ''],
    ['title' => 'Top Stocks', 'value' => 'Apple : 1', 'sub' => 'Only 1'],
    ['title' => 'Top Category', 'value' => 'Fruit : 1', 'sub' => ''],
    ['title' => 'Total Receipt Count', 'value' => '1', 'sub' => ''],
    ['title' => 'Tax', 'value' => '₱0.00', 'sub' => ''],
    ['title' => 'Discount', 'value' => '₱0.00', 'sub' => ''],
    ['title' => 'Avg Sales Value', 'value' => '₱12.00', 'sub' => ''],
    ['title' => 'Top Customer', 'value' => '', 'sub' => 'No Sales Link to any Customer!'],
    ['title' => 'Payment Modes', 'value' => 'Cash : ₱12.00', 'sub' => ''],
    ['title' => 'Sold By', 'value' => 'Joshua Mark Playda', 'sub' => 'only 1 Cashier'],
  ];
@endphp

<header class="topbar">
  <button class="icon-btn show-mobile" id="openSidebar" aria-label="Open menu">
    <span class="material-symbols-outlined">menu</span>
  </button>

  <div class="topbar-left">
    <div class="hello">
      <div class="hello-title">
        Hello, <strong>{{ $admin->first_name ?? 'Owner' }}</strong>
      </div>
      <div class="hello-sub"></div>
    </div>
  </div>

  <div class="topbar-right">
    <button class="icon-btn" aria-label="Notifications">
      <span class="material-symbols-outlined">notifications</span>
    </button>

    <button class="icon-btn" id="openReportShareModal" aria-label="Share">
      <span class="material-symbols-outlined">share</span>
    </button>

    <div class="avatar">
      <span class="material-symbols-outlined">chat</span>
    </div>
  </div>
</header>

<div class="reports-page">
  <div class="reports-toolbar">
    <div class="report-date-nav">
      <button type="button" class="date-nav-btn left" id="dateBackBtn" aria-label="Previous">
  <span class="material-symbols-outlined">arrow_back</span>
</button>
      <button type="button" class="report-date-chip" id="openDateFilterModal" aria-label="Open date filter">
        <span class="material-symbols-outlined">calendar_month</span>
        <span id="reportDateLabel">Today : 24 Mar</span>
      </button>

      <button type="button" class="date-nav-btn right is-hidden" id="dateForwardBtn" aria-label="Next">
        <span class="material-symbols-outlined">arrow_forward</span>
      </button>
    </div>
  </div>

<div class="reports-grid">
  @foreach($reportCards as $card)
    <div class="report-card open-total-sales-modal" role="button" tabindex="0">
      <div class="report-card-main">
        <div class="report-card-title">{{ $card['title'] }}</div>

        @if($card['value'] !== '')
          <div class="report-card-value">{{ $card['value'] }}</div>
        @endif

        @if($card['sub'] !== '')
          <div class="report-card-sub">{{ $card['sub'] }}</div>
        @endif
      </div>

      <div class="report-card-arrow">
        <span class="material-symbols-outlined">chevron_right</span>
      </div>
    </div>
  @endforeach
</div>
</div>

<div class="report-share-modal" id="reportShareModal">
  <div class="report-share-sheet">
    <div class="report-share-topbar">
      <button type="button" class="report-share-back" id="closeReportShareModal" aria-label="Back">
        <span class="material-symbols-outlined">arrow_back</span>
      </button>
      <h3>Report Share</h3>
    </div>

    <div class="report-share-store">
      <span class="material-symbols-outlined">store</span>
      <span>Fyng</span>
    </div>

    <div class="report-share-content">
      <div class="report-share-info-card">
        <div class="share-info-left">
          <div class="share-info-label">Generated by</div>
          <div class="share-info-name">Joshua Mark Playda</div>
          <div class="share-info-email">joshua.playda.7@gmail.com</div>
        </div>

        <div class="share-info-right">
          <div class="share-info-label">Date</div>
          <div class="share-info-date">Today : 24 Mar</div>
        </div>
      </div>

      <div class="report-share-list">
        @foreach($reportCards as $card)
          <div class="report-share-card">
            <div class="report-share-main">
              <div class="report-share-title">{{ $card['title'] }}</div>

              @if($card['value'] !== '')
                <div class="report-share-value">{{ $card['value'] }}</div>
              @endif

              @if($card['sub'] !== '')
                <div class="report-share-sub">{{ $card['sub'] }}</div>
              @endif
            </div>

            <div class="report-share-arrow">
              <span class="material-symbols-outlined">chevron_right</span>
            </div>
          </div>
        @endforeach
      </div>
    </div>

    <button type="button" class="floating-share-btn" id="openShareFileModal" aria-label="Share report">
      <span class="material-symbols-outlined">share</span>
    </button>
  </div>
</div>

<div class="share-file-modal" id="shareFileModal">
  <div class="share-file-card">
    <button type="button" class="share-file-close" id="closeShareFileModal" aria-label="Close">
      <span class="material-symbols-outlined">close</span>
    </button>

    <div class="share-file-body">
      <div class="share-file-icon-wrap">
        <div class="share-file-icon-bg">
          <span class="material-symbols-outlined">description</span>
        </div>
      </div>

      <div class="share-file-name">Report__1774345367944.pdf</div>
      <div class="share-file-size">57.54 KB</div>
    </div>

    <div class="share-file-actions">
      <button type="button" class="share-file-text-btn">Save As</button>
      <button type="button" class="share-file-action-btn open">Open</button>
      <button type="button" class="share-file-action-btn share">Share</button>
    </div>
  </div>
</div>

<div class="date-filter-modal" id="dateFilterModal">
  <div class="date-filter-sheet">
    <div class="date-filter-topbar">
      <button type="button" class="date-filter-close" id="closeDateFilterModal" aria-label="Close">
        <span class="material-symbols-outlined">close</span>
      </button>
      <h3>Filter By Date</h3>
    </div>

    <div class="date-filter-body">
      <div class="date-filter-title">Select Date Range</div>

      <div class="date-filter-inputs">
        <input type="text" id="reportStartDate" class="date-filter-input" placeholder="Start Date">
        <input type="text" id="reportEndDate" class="date-filter-input" placeholder="End Date">
      </div>

      <button type="button" class="date-filter-show-btn" id="applyDateFilter">
        Show Reports
      </button>

      <div class="date-filter-grid">
  <button type="button" class="date-preset-btn" data-range="today">Today</button>
  <button type="button" class="date-preset-btn" data-range="yesterday">Yesterday</button>
  <button type="button" class="date-preset-btn" data-range="this_week">This Week</button>
  <button type="button" class="date-preset-btn" data-range="last_week">Last Week</button>
  <button type="button" class="date-preset-btn" data-range="this_month">This Month</button>
  <button type="button" class="date-preset-btn" data-range="last_month">Last Month</button>
  <button type="button" class="date-preset-btn" data-range="this_year">This Year</button>
  <button type="button" class="date-preset-btn" data-range="last_year">Last Year</button>
</div>
    </div>
  </div>
</div>
@include('admin.home.reports.total_sales')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
document.addEventListener("DOMContentLoaded", function () {
  /* =========================
     SHARE MODALS
  ========================= */
  const openReportShareModal = document.getElementById("openReportShareModal");
  const closeReportShareModal = document.getElementById("closeReportShareModal");
  const reportShareModal = document.getElementById("reportShareModal");

  const openShareFileModal = document.getElementById("openShareFileModal");
  const closeShareFileModal = document.getElementById("closeShareFileModal");
  const shareFileModal = document.getElementById("shareFileModal");

  function showReportShareModal() {
    reportShareModal?.classList.add("show");
    document.body.classList.add("no-scroll");
  }

  function hideReportShareModal() {
    reportShareModal?.classList.remove("show");
    document.body.classList.remove("no-scroll");
  }

  function showShareFileModal() {
    shareFileModal?.classList.add("show");
  }

  function hideShareFileModal() {
    shareFileModal?.classList.remove("show");
  }

  openReportShareModal?.addEventListener("click", function (e) {
    e.stopPropagation();
    showReportShareModal();
  });

  closeReportShareModal?.addEventListener("click", function () {
    hideReportShareModal();
  });

  reportShareModal?.addEventListener("click", function (e) {
    if (e.target === reportShareModal) {
      hideReportShareModal();
    }
  });

  openShareFileModal?.addEventListener("click", function (e) {
    e.stopPropagation();
    showShareFileModal();
  });

  closeShareFileModal?.addEventListener("click", function () {
    hideShareFileModal();
  });

  shareFileModal?.addEventListener("click", function (e) {
    if (e.target === shareFileModal) {
      hideShareFileModal();
    }
  });

  /* =========================
     DATE FILTER MODAL
  ========================= */
  const openDateFilterModal = document.getElementById("openDateFilterModal");
  const closeDateFilterModal = document.getElementById("closeDateFilterModal");
  const dateFilterModal = document.getElementById("dateFilterModal");
  const applyDateFilter = document.getElementById("applyDateFilter");
  const reportDateLabel = document.getElementById("reportDateLabel");
  const dateBackBtn = document.getElementById("dateBackBtn");
  const dateForwardBtn = document.getElementById("dateForwardBtn");
  const reportStartDate = document.getElementById("reportStartDate");
  const reportEndDate = document.getElementById("reportEndDate");

  const PH_TIMEZONE = "Asia/Manila";

  function getPHDateParts(date = new Date()) {
    const parts = new Intl.DateTimeFormat("en-CA", {
      timeZone: PH_TIMEZONE,
      year: "numeric",
      month: "2-digit",
      day: "2-digit"
    }).formatToParts(date);

    return {
      year: Number(parts.find(p => p.type === "year").value),
      month: Number(parts.find(p => p.type === "month").value),
      day: Number(parts.find(p => p.type === "day").value)
    };
  }

  function getTodayPH() {
    const { year, month, day } = getPHDateParts();
    return new Date(year, month - 1, day);
  }

  function cloneDate(date) {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  }

  function addDays(date, days) {
    const d = cloneDate(date);
    d.setDate(d.getDate() + days);
    return d;
  }

  function startOfWeek(date) {
    const d = cloneDate(date);
    const day = d.getDay(); // Sunday start
    return addDays(d, -day);
  }

  function endOfWeek(date) {
    return addDays(startOfWeek(date), 6);
  }

  function startOfMonth(date) {
    return new Date(date.getFullYear(), date.getMonth(), 1);
  }

  function endOfMonth(date) {
    return new Date(date.getFullYear(), date.getMonth() + 1, 0);
  }

  function startOfYear(date) {
    return new Date(date.getFullYear(), 0, 1);
  }

  function endOfYear(date) {
    return new Date(date.getFullYear(), 11, 31);
  }

  function addMonths(date, months) {
    return new Date(date.getFullYear(), date.getMonth() + months, 1);
  }

  function addYears(date, years) {
    return new Date(date.getFullYear() + years, 0, 1);
  }

  function sameDate(a, b) {
    return a.getFullYear() === b.getFullYear() &&
           a.getMonth() === b.getMonth() &&
           a.getDate() === b.getDate();
  }

  function toInputValue(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  }

  function fromInputValue(value) {
    if (!value) return null;
    const [y, m, d] = value.split("-").map(Number);
    return new Date(y, m - 1, d);
  }

  function formatDayShort(date) {
    return date.toLocaleDateString("en-PH", {
      timeZone: PH_TIMEZONE,
      day: "numeric",
      month: "short"
    });
  }

  function formatDayFull(date) {
    return date.toLocaleDateString("en-PH", {
      timeZone: PH_TIMEZONE,
      day: "2-digit",
      month: "short",
      year: "numeric"
    });
  }

  const state = {
    type: "preset",
    preset: "today",
    anchorDate: getTodayPH(),
    customStart: null,
    customEnd: null
  };

function getPresetRange(preset, anchor = getTodayPH()) {
  const today = getTodayPH();
  const base = cloneDate(anchor);
  const actualYesterday = addDays(today, -1);

  switch (preset) {
    case "today": {
      if (sameDate(base, today)) {
        return {
          start: base,
          end: base,
          label: `Today : ${formatDayShort(base)}`,
          showForward: false
        };
      }

      if (sameDate(base, actualYesterday)) {
        return {
          start: base,
          end: base,
          label: `Yesterday: ${formatDayShort(base)}`,
          showForward: true
        };
      }

      return {
        start: base,
        end: base,
        label: formatDayFull(base),
        showForward: true
      };
    }

    case "yesterday": {
      if (sameDate(base, actualYesterday)) {
        return {
          start: base,
          end: base,
          label: `Yesterday: ${formatDayShort(base)}`,
          showForward: true
        };
      }

      if (sameDate(base, today)) {
        return {
          start: base,
          end: base,
          label: `Today : ${formatDayShort(base)}`,
          showForward: false
        };
      }

      return {
        start: base,
        end: base,
        label: formatDayFull(base),
        showForward: true
      };
    }

    case "this_week": {
      const start = startOfWeek(base);
      let end = endOfWeek(base);

      if (end > today) end = today;

      return {
        start,
        end,
        label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
        showForward: !sameDate(end, today)
      };
    }

    case "last_week": {
      const currentWeekStart = startOfWeek(today);
      const currentWeekEnd = today;
      const previousWeekStart = addDays(currentWeekStart, -7);
      const previousWeekEnd = addDays(currentWeekStart, -1);

      const start = startOfWeek(base);
      const end = endOfWeek(base);

      if (sameDate(start, previousWeekStart) && sameDate(end, previousWeekEnd)) {
        return {
          start,
          end,
          label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
          showForward: true
        };
      }

      if (sameDate(start, currentWeekStart)) {
        return {
          start: currentWeekStart,
          end: currentWeekEnd,
          label: `${formatDayFull(currentWeekStart)} - ${formatDayFull(currentWeekEnd)}`,
          showForward: false
        };
      }

      return {
        start,
        end,
        label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
        showForward: true
      };
    }

    case "this_month": {
      const start = startOfMonth(base);
      let end = endOfMonth(base);

      if (
        base.getFullYear() === today.getFullYear() &&
        base.getMonth() === today.getMonth()
      ) {
        end = today;
      }

      return {
        start,
        end,
        label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
        showForward: !sameDate(end, today)
      };
    }

    case "last_month": {
      const currentMonthStart = startOfMonth(today);
      const currentMonthEnd = today;
      const previousMonthBase = addMonths(today, -1);
      const previousMonthStart = startOfMonth(previousMonthBase);
      const previousMonthEnd = endOfMonth(previousMonthBase);

      const start = startOfMonth(base);
      const end = endOfMonth(base);

      if (sameDate(start, previousMonthStart) && sameDate(end, previousMonthEnd)) {
        return {
          start,
          end,
          label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
          showForward: true
        };
      }

      if (
        start.getFullYear() === currentMonthStart.getFullYear() &&
        start.getMonth() === currentMonthStart.getMonth()
      ) {
        return {
          start: currentMonthStart,
          end: currentMonthEnd,
          label: `${formatDayFull(currentMonthStart)} - ${formatDayFull(currentMonthEnd)}`,
          showForward: false
        };
      }

      return {
        start,
        end,
        label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
        showForward: true
      };
    }

    case "this_year": {
      const start = startOfYear(base);
      let end = endOfYear(base);

      if (base.getFullYear() === today.getFullYear()) {
        end = today;
      }

      return {
        start,
        end,
        label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
        showForward: !sameDate(end, today)
      };
    }

    case "last_year": {
      const currentYearStart = startOfYear(today);
      const currentYearEnd = today;
      const previousYear = today.getFullYear() - 1;

      const start = startOfYear(base);
      const end = endOfYear(base);

      if (start.getFullYear() === previousYear) {
        return {
          start,
          end,
          label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
          showForward: true
        };
      }

      if (start.getFullYear() === today.getFullYear()) {
        return {
          start: currentYearStart,
          end: currentYearEnd,
          label: `${formatDayFull(currentYearStart)} - ${formatDayFull(currentYearEnd)}`,
          showForward: false
        };
      }

      return {
        start,
        end,
        label: `${formatDayFull(start)} - ${formatDayFull(end)}`,
        showForward: true
      };
    }

    default:
      return {
        start: today,
        end: today,
        label: `Today : ${formatDayShort(today)}`,
        showForward: false
      };
  }
}

function movePresetAnchor(direction) {
  const today = getTodayPH();

  switch (state.preset) {
    case "today":
    case "yesterday":
      state.anchorDate = addDays(state.anchorDate, direction);
      if (state.anchorDate > today) state.anchorDate = today;
      break;

    case "this_week":
    case "last_week":
      state.anchorDate = addDays(state.anchorDate, direction * 7);
      if (state.anchorDate > today) state.anchorDate = today;
      break;

    case "this_month":
    case "last_month":
      state.anchorDate = addMonths(state.anchorDate, direction);
      if (
        state.anchorDate.getFullYear() > today.getFullYear() ||
        (state.anchorDate.getFullYear() === today.getFullYear() &&
         state.anchorDate.getMonth() > today.getMonth())
      ) {
        state.anchorDate = today;
      }
      break;

    case "this_year":
    case "last_year":
      state.anchorDate = addYears(state.anchorDate, direction);
      if (state.anchorDate.getFullYear() > today.getFullYear()) {
        state.anchorDate = today;
      }
      break;
  }
}
  function renderDateNav() {
    const today = getTodayPH();

    if (state.type === "preset") {
      const range = getPresetRange(state.preset, state.anchorDate);
      reportDateLabel.textContent = range.label;
      dateForwardBtn.classList.toggle("is-hidden", !range.showForward);
      return;
    }

    const start = fromInputValue(state.customStart);
    const end = fromInputValue(state.customEnd);

    if (start && end) {
      reportDateLabel.textContent = `${formatDayFull(start)} - ${formatDayFull(end)}`;
      dateForwardBtn.classList.toggle("is-hidden", sameDate(end, today));
    } else {
      reportDateLabel.textContent = `Today : ${formatDayShort(today)}`;
      dateForwardBtn.classList.add("is-hidden");
    }
  }

  function syncInputsFromState() {
    if (state.type === "preset") {
      const range = getPresetRange(state.preset, state.anchorDate);
      if (reportStartDate) reportStartDate.value = toInputValue(range.start);
      if (reportEndDate) reportEndDate.value = toInputValue(range.end);
      return;
    }

    const start = fromInputValue(state.customStart);
    const end = fromInputValue(state.customEnd);

    if (reportStartDate && start) reportStartDate.value = toInputValue(start);
    if (reportEndDate && end) reportEndDate.value = toInputValue(end);
  }

  function showDateFilterModal() {
    syncInputsFromState();
    dateFilterModal?.classList.add("show");
    document.body.classList.add("no-scroll");
  }

  function hideDateFilterModal() {
    dateFilterModal?.classList.remove("show");
    document.body.classList.remove("no-scroll");
  }

  openDateFilterModal?.addEventListener("click", function (e) {
    e.stopPropagation();
    showDateFilterModal();
  });

  closeDateFilterModal?.addEventListener("click", hideDateFilterModal);

  dateFilterModal?.addEventListener("click", function (e) {
    if (e.target === dateFilterModal) {
      hideDateFilterModal();
    }
  });

  document.querySelectorAll(".date-preset-btn").forEach(button => {
    button.addEventListener("click", function () {
      const today = getTodayPH();
      state.type = "preset";
      state.preset = this.dataset.range;

      switch (state.preset) {
        case "today":
          state.anchorDate = today;
          break;
        case "yesterday":
          state.anchorDate = addDays(today, -1);
          break;
        case "this_week":
          state.anchorDate = today;
          break;
        case "last_week":
          state.anchorDate = addDays(today, -7);
          break;
        case "this_month":
          state.anchorDate = today;
          break;
        case "last_month":
          state.anchorDate = addMonths(today, -1);
          break;
        case "this_year":
          state.anchorDate = today;
          break;
        case "last_year":
          state.anchorDate = addYears(today, -1);
          break;
      }

      renderDateNav();
      syncInputsFromState();
      hideDateFilterModal();
    });
  });

  applyDateFilter?.addEventListener("click", function () {
    const startVal = reportStartDate?.value?.trim();
    const endVal = reportEndDate?.value?.trim();

    if (startVal && endVal) {
      state.type = "custom";
      state.customStart = startVal;
      state.customEnd = endVal;
      renderDateNav();
    }

    hideDateFilterModal();
  });

  dateBackBtn?.addEventListener("click", function (e) {
    e.stopPropagation();

    if (state.type === "preset") {
      movePresetAnchor(-1);
      renderDateNav();
      syncInputsFromState();
      return;
    }

    const start = fromInputValue(state.customStart);
    const end = fromInputValue(state.customEnd);
    if (!start || !end) return;

    const diffDays = Math.round((end - start) / 86400000);
    const nextStart = addDays(start, -(diffDays + 1));
    const nextEnd = addDays(end, -(diffDays + 1));

    state.customStart = toInputValue(nextStart);
    state.customEnd = toInputValue(nextEnd);
    renderDateNav();
    syncInputsFromState();
  });

  dateForwardBtn?.addEventListener("click", function (e) {
    e.stopPropagation();

    const today = getTodayPH();

    if (state.type === "preset") {
      movePresetAnchor(1);
      renderDateNav();
      syncInputsFromState();
      return;
    }

    const start = fromInputValue(state.customStart);
    const end = fromInputValue(state.customEnd);
    if (!start || !end) return;

    const diffDays = Math.round((end - start) / 86400000);
    let nextStart = addDays(start, diffDays + 1);
    let nextEnd = addDays(end, diffDays + 1);

    if (nextEnd > today) {
      nextEnd = today;
      nextStart = addDays(today, -diffDays);
    }

    state.customStart = toInputValue(nextStart);
    state.customEnd = toInputValue(nextEnd);
    renderDateNav();
    syncInputsFromState();
  });

  if (reportStartDate) {
    flatpickr(reportStartDate, {
      dateFormat: "Y-m-d",
      defaultDate: "today",
      maxDate: "today"
    });
  }

  if (reportEndDate) {
    flatpickr(reportEndDate, {
      dateFormat: "Y-m-d",
      defaultDate: "today",
      maxDate: "today"
    });
  }

  renderDateNav();
  syncInputsFromState();

});
</script>
@include('admin.home')

@endsection